[Interface]
Address = 10.21.0.1/24
PrivateKey = EznzRIMa0XW1IKZUkWKdd2LMds+EwtAW+NkOeRAxgnA=
ListenPort = 51821
DNS = 1.1.1.1

[Peer]
# Alias = peer-04
PublicKey = FkN+Ch9XRaWk+Fb0FyBobNEkKGU8OSaxNe1C9OmqzZE=
AllowedIPs = 10.21.0.10/32
Endpoint = 198.51.100.12:51820

[Peer]
# Alias = peer-05
PublicKey = ZsEKnwCoSyPNlZJ0Oxe1+Z3qLPAQ+Ebs0VZOq/BYcyk=
AllowedIPs = 10.21.0.11/32
Endpoint = 198.51.100.13:51820

[Peer]
# Alias = peer-06
PublicKey = Ek6fjFNQ87myJePoJtr+pm5hWWoBlvj/xXvVTGG2fq4=
AllowedIPs = 10.21.0.12/32
Endpoint = 198.51.100.19:51820
