[Interface]
Address = 10.22.0.1/24
PrivateKey = rKgPAHPXZoUxNyiieOWOtHP5ot+9TIW//CZxTg9PRT8=
ListenPort = 51822
DNS = 9.9.9.9

[Peer]
# Alias = peer-07
PublicKey = IYAaBfH17FOodTqPaXKO0Vb2TFbUXld1AsaeK/Xmf8U=
AllowedIPs = 10.22.0.10/32
Endpoint = 198.51.100.14:51820

[Peer]
# Alias = peer-08
PublicKey = kQjZRic2ApLtzdArsDCQ+1o0bbSHc9WheeTb0il0xb0=
AllowedIPs = 10.22.0.11/32
Endpoint = 198.51.100.15:51820

[Peer]
# Alias = peer-09
PublicKey = YeTMKZ/DvjT/xHWPA4DZcu4j3paArQMfby9CCMT3MGI=
AllowedIPs = 10.22.0.12/32
Endpoint = 198.51.100.20:51820
