// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Admin struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type DailyUsage struct {
	User     string `json:"user"`
	Ts       int64  `json:"ts"`
	Uplink   int64  `json:"uplink"`
	Downlink int64  `json:"downlink"`
}

type DailyWgUsage struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Rx        int64  `json:"rx"`
	Tx        int64  `json:"tx"`
}

type ImportState struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type InboundMetum struct {
	Tag          string         `json:"tag"`
	ExternalPort sql.NullInt64  `json:"external_port"`
	ClientSni    sql.NullString `json:"client_sni"`
}

type PanelUser struct {
	Username           string        `json:"username"`
	PasswordHash       string        `json:"password_hash"`
	CanReadUsers       int64         `json:"can_read_users"`
	CanWriteUsers      int64         `json:"can_write_users"`
	CanReadWireguard   int64         `json:"can_read_wireguard"`
	CanWriteWireguard  int64         `json:"can_write_wireguard"`
	CanReadConfig      int64         `json:"can_read_config"`
	CanWriteConfig     int64         `json:"can_write_config"`
	CanReadSettings    int64         `json:"can_read_settings"`
	CanWriteSettings   int64         `json:"can_write_settings"`
	CanReadPanelUsers  int64         `json:"can_read_panel_users"`
	CanWritePanelUsers int64         `json:"can_write_panel_users"`
	CanReadLogs        int64         `json:"can_read_logs"`
	CreatedAt          sql.NullInt64 `json:"created_at"`
	UpdatedAt          sql.NullInt64 `json:"updated_at"`
}

type Sample struct {
	User     string `json:"user"`
	Ts       int64  `json:"ts"`
	Uplink   int64  `json:"uplink"`
	Downlink int64  `json:"downlink"`
}

type SamplerRun struct {
	ID         int64          `json:"id"`
	Ts         int64          `json:"ts"`
	DurationMs int64          `json:"duration_ms"`
	Inserted   int64          `json:"inserted"`
	Error      sql.NullString `json:"error"`
	Source     sql.NullString `json:"source"`
}

type Subscription struct {
	ID                         int64          `json:"id"`
	Token                      string         `json:"token"`
	Name                       string         `json:"name"`
	QuotaLimit                 sql.NullInt64  `json:"quota_limit"`
	QuotaPeriod                sql.NullString `json:"quota_period"`
	ResetDay                   sql.NullInt64  `json:"reset_day"`
	ProfileUpdateIntervalHours sql.NullInt64  `json:"profile_update_interval_hours"`
	UpdateAlways               int64          `json:"update_always"`
	LastRequestAt              sql.NullInt64  `json:"last_request_at"`
	CreatedAt                  sql.NullInt64  `json:"created_at"`
	UpdatedAt                  sql.NullInt64  `json:"updated_at"`
}

type SubscriptionRequest struct {
	ID              int64  `json:"id"`
	SubID           int64  `json:"sub_id"`
	UserName        string `json:"user_name"`
	RequestIP       string `json:"request_ip"`
	RequestedAt     int64  `json:"requested_at"`
	ServedFromCache int64  `json:"served_from_cache"`
}

type SubscriptionUser struct {
	SubID    int64  `json:"sub_id"`
	UserName string `json:"user_name"`
}

type User struct {
	Email         string         `json:"email"`
	QuotaLimit    sql.NullInt64  `json:"quota_limit"`
	QuotaPeriod   sql.NullString `json:"quota_period"`
	ResetDay      sql.NullInt64  `json:"reset_day"`
	Enabled       sql.NullInt64  `json:"enabled"`
	VmessSecurity sql.NullString `json:"vmess_security"`
	VmessAlterID  sql.NullInt64  `json:"vmess_alter_id"`
}

type WgPeer struct {
	PublicKey     string        `json:"public_key"`
	Alias         string        `json:"alias"`
	LastHandshake sql.NullInt64 `json:"last_handshake"`
	Deleted       sql.NullInt64 `json:"deleted"`
	CreatedAt     sql.NullInt64 `json:"created_at"`
	UpdatedAt     sql.NullInt64 `json:"updated_at"`
}

type WgSample struct {
	PublicKey string         `json:"public_key"`
	Ts        int64          `json:"ts"`
	Rx        int64          `json:"rx"`
	Tx        int64          `json:"tx"`
	Endpoint  sql.NullString `json:"endpoint"`
}
