// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addUserToSubscription = `-- name: AddUserToSubscription :exec
INSERT OR IGNORE INTO subscription_users (sub_id, user_name) VALUES (?, ?)
`

type AddUserToSubscriptionParams struct {
	SubID    int64  `json:"sub_id"`
	UserName string `json:"user_name"`
}

// Subscription Users Queries --
func (q *Queries) AddUserToSubscription(ctx context.Context, arg AddUserToSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addUserToSubscription, arg.SubID, arg.UserName)
	return err
}

const checkAdminExists = `-- name: CheckAdminExists :one
SELECT COUNT(*) FROM admins WHERE username = ?
`

func (q *Queries) CheckAdminExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAdminExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPanelUserExists = `-- name: CheckPanelUserExists :one
SELECT COUNT(*) FROM panel_users WHERE username = ?
`

func (q *Queries) CheckPanelUserExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPanelUserExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearSubscriptionUsers = `-- name: ClearSubscriptionUsers :exec
DELETE FROM subscription_users WHERE sub_id = ?
`

func (q *Queries) ClearSubscriptionUsers(ctx context.Context, subID int64) error {
	_, err := q.db.ExecContext(ctx, clearSubscriptionUsers, subID)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDailyUsage = `-- name: CountDailyUsage :one
SELECT COUNT(*) FROM daily_usage
`

func (q *Queries) CountDailyUsage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDailyUsage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPanelUsers = `-- name: CountPanelUsers :one
SELECT COUNT(*) FROM panel_users
`

func (q *Queries) CountPanelUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPanelUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSamples = `-- name: CountSamples :one
SELECT COUNT(*) FROM samples
`

// Samples Queries --
func (q *Queries) CountSamples(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSamples)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWGDailyUsage = `-- name: CountWGDailyUsage :one
SELECT COUNT(*) FROM daily_wg_usage
`

func (q *Queries) CountWGDailyUsage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWGDailyUsage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWGSamples = `-- name: CountWGSamples :one
SELECT COUNT(*) FROM wg_samples
`

// WireGuard Samples --
func (q *Queries) CountWGSamples(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWGSamples)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (username, password_hash) VALUES (?, ?)
`

type CreateAdminParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

// Admin Queries --
func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.ExecContext(ctx, createAdmin, arg.Username, arg.PasswordHash)
	return err
}

const createPanelUser = `-- name: CreatePanelUser :exec
INSERT INTO panel_users (
	username,
	password_hash,
	can_read_users,
	can_write_users,
	can_read_wireguard,
	can_write_wireguard,
	can_read_config,
	can_write_config,
	can_read_settings,
	can_write_settings,
	can_read_panel_users,
	can_write_panel_users,
	can_read_logs
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePanelUserParams struct {
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	CanReadUsers       int64  `json:"can_read_users"`
	CanWriteUsers      int64  `json:"can_write_users"`
	CanReadWireguard   int64  `json:"can_read_wireguard"`
	CanWriteWireguard  int64  `json:"can_write_wireguard"`
	CanReadConfig      int64  `json:"can_read_config"`
	CanWriteConfig     int64  `json:"can_write_config"`
	CanReadSettings    int64  `json:"can_read_settings"`
	CanWriteSettings   int64  `json:"can_write_settings"`
	CanReadPanelUsers  int64  `json:"can_read_panel_users"`
	CanWritePanelUsers int64  `json:"can_write_panel_users"`
	CanReadLogs        int64  `json:"can_read_logs"`
}

// Panel Users Queries --
func (q *Queries) CreatePanelUser(ctx context.Context, arg CreatePanelUserParams) error {
	_, err := q.db.ExecContext(ctx, createPanelUser,
		arg.Username,
		arg.PasswordHash,
		arg.CanReadUsers,
		arg.CanWriteUsers,
		arg.CanReadWireguard,
		arg.CanWriteWireguard,
		arg.CanReadConfig,
		arg.CanWriteConfig,
		arg.CanReadSettings,
		arg.CanWriteSettings,
		arg.CanReadPanelUsers,
		arg.CanWritePanelUsers,
		arg.CanReadLogs,
	)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (token, name) VALUES (?, ?) RETURNING id
`

type CreateSubscriptionParams struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

// Subscriptions Queries --
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSubscription, arg.Token, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteInboundMeta = `-- name: DeleteInboundMeta :exec
DELETE FROM inbound_meta WHERE tag = ?
`

func (q *Queries) DeleteInboundMeta(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, deleteInboundMeta, tag)
	return err
}

const deletePanelUser = `-- name: DeletePanelUser :exec
DELETE FROM panel_users WHERE username = ?
`

func (q *Queries) DeletePanelUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deletePanelUser, username)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE email = ?
`

func (q *Queries) DeleteUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, email)
	return err
}

const getActiveUserCount = `-- name: GetActiveUserCount :one
SELECT COUNT(DISTINCT user)
FROM samples
WHERE ts >= ? AND (uplink > 0 OR downlink > 0)
`

func (q *Queries) GetActiveUserCount(ctx context.Context, ts int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserCount, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveUserCountWithThreshold = `-- name: GetActiveUserCountWithThreshold :one
SELECT COUNT(*) FROM (
	SELECT user, SUM(uplink + downlink) as total
	FROM samples
	WHERE ts >= ?
	GROUP BY user
	HAVING SUM(uplink + downlink) >= ?
)
`

type GetActiveUserCountWithThresholdParams struct {
	Ts     int64 `json:"ts"`
	Uplink int64 `json:"uplink"`
}

func (q *Queries) GetActiveUserCountWithThreshold(ctx context.Context, arg GetActiveUserCountWithThresholdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserCountWithThreshold, arg.Ts, arg.Uplink)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveUsersWithThreshold = `-- name: GetActiveUsersWithThreshold :many
SELECT user, SUM(uplink + downlink) as total 
FROM samples 
WHERE ts >= ? 
GROUP BY user 
HAVING SUM(uplink + downlink) >= ?
`

type GetActiveUsersWithThresholdParams struct {
	Ts     int64 `json:"ts"`
	Uplink int64 `json:"uplink"`
}

type GetActiveUsersWithThresholdRow struct {
	User  string          `json:"user"`
	Total sql.NullFloat64 `json:"total"`
}

func (q *Queries) GetActiveUsersWithThreshold(ctx context.Context, arg GetActiveUsersWithThresholdParams) ([]GetActiveUsersWithThresholdRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsersWithThreshold, arg.Ts, arg.Uplink)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUsersWithThresholdRow
	for rows.Next() {
		var i GetActiveUsersWithThresholdRow
		if err := rows.Scan(&i.User, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveUsersWithTraffic = `-- name: GetActiveUsersWithTraffic :many
SELECT DISTINCT user 
FROM samples 
WHERE ts >= ? AND (uplink > 0 OR downlink > 0)
`

func (q *Queries) GetActiveUsersWithTraffic(ctx context.Context, ts int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsersWithTraffic, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user string
		if err := rows.Scan(&user); err != nil {
			return nil, err
		}
		items = append(items, user)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdmin = `-- name: GetAdmin :one
SELECT password_hash FROM admins WHERE username = ?
`

func (q *Queries) GetAdmin(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, username)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getAllInboundMeta = `-- name: GetAllInboundMeta :many
SELECT tag, external_port FROM inbound_meta
`

type GetAllInboundMetaRow struct {
	Tag          string        `json:"tag"`
	ExternalPort sql.NullInt64 `json:"external_port"`
}

func (q *Queries) GetAllInboundMeta(ctx context.Context) ([]GetAllInboundMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllInboundMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInboundMetaRow
	for rows.Next() {
		var i GetAllInboundMetaRow
		if err := rows.Scan(&i.Tag, &i.ExternalPort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPanelUsers = `-- name: GetAllPanelUsers :many
SELECT
	username,
	can_read_users,
	can_write_users,
	can_read_wireguard,
	can_write_wireguard,
	can_read_config,
	can_write_config,
	can_read_settings,
	can_write_settings,
	can_read_panel_users,
	can_write_panel_users,
	can_read_logs,
	created_at
FROM panel_users
ORDER BY username ASC
`

type GetAllPanelUsersRow struct {
	Username           string        `json:"username"`
	CanReadUsers       int64         `json:"can_read_users"`
	CanWriteUsers      int64         `json:"can_write_users"`
	CanReadWireguard   int64         `json:"can_read_wireguard"`
	CanWriteWireguard  int64         `json:"can_write_wireguard"`
	CanReadConfig      int64         `json:"can_read_config"`
	CanWriteConfig     int64         `json:"can_write_config"`
	CanReadSettings    int64         `json:"can_read_settings"`
	CanWriteSettings   int64         `json:"can_write_settings"`
	CanReadPanelUsers  int64         `json:"can_read_panel_users"`
	CanWritePanelUsers int64         `json:"can_write_panel_users"`
	CanReadLogs        int64         `json:"can_read_logs"`
	CreatedAt          sql.NullInt64 `json:"created_at"`
}

func (q *Queries) GetAllPanelUsers(ctx context.Context) ([]GetAllPanelUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPanelUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPanelUsersRow
	for rows.Next() {
		var i GetAllPanelUsersRow
		if err := rows.Scan(
			&i.Username,
			&i.CanReadUsers,
			&i.CanWriteUsers,
			&i.CanReadWireguard,
			&i.CanWriteWireguard,
			&i.CanReadConfig,
			&i.CanWriteConfig,
			&i.CanReadSettings,
			&i.CanWriteSettings,
			&i.CanReadPanelUsers,
			&i.CanWritePanelUsers,
			&i.CanReadLogs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, token, name, created_at, updated_at FROM subscriptions ORDER BY created_at DESC
`

func (q *Queries) GetAllSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT email, quota_limit, quota_period, reset_day, enabled, vmess_security, vmess_alter_id FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Email,
			&i.QuotaLimit,
			&i.QuotaPeriod,
			&i.ResetDay,
			&i.Enabled,
			&i.VmessSecurity,
			&i.VmessAlterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWGPeers = `-- name: GetAllWGPeers :many
SELECT public_key, alias, last_handshake, deleted FROM wg_peers
`

type GetAllWGPeersRow struct {
	PublicKey     string        `json:"public_key"`
	Alias         string        `json:"alias"`
	LastHandshake sql.NullInt64 `json:"last_handshake"`
	Deleted       sql.NullInt64 `json:"deleted"`
}

func (q *Queries) GetAllWGPeers(ctx context.Context) ([]GetAllWGPeersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWGPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWGPeersRow
	for rows.Next() {
		var i GetAllWGPeersRow
		if err := rows.Scan(
			&i.PublicKey,
			&i.Alias,
			&i.LastHandshake,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyUsageInDateRange = `-- name: GetDailyUsageInDateRange :many
SELECT user, ts, uplink, downlink
FROM daily_usage
WHERE user = ? AND ts >= ? AND ts <= ?
`

type GetDailyUsageInDateRangeParams struct {
	User string `json:"user"`
	Ts   int64  `json:"ts"`
	Ts_2 int64  `json:"ts_2"`
}

func (q *Queries) GetDailyUsageInDateRange(ctx context.Context, arg GetDailyUsageInDateRangeParams) ([]DailyUsage, error) {
	rows, err := q.db.QueryContext(ctx, getDailyUsageInDateRange, arg.User, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyUsage
	for rows.Next() {
		var i DailyUsage
		if err := rows.Scan(
			&i.User,
			&i.Ts,
			&i.Uplink,
			&i.Downlink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalTraffic = `-- name: GetGlobalTraffic :many
SELECT ts, SUM(uplink) as up, SUM(downlink) as down
FROM samples
WHERE ts >= ? AND ts <= ?
GROUP BY ts
ORDER BY ts ASC
`

type GetGlobalTrafficParams struct {
	Ts   int64 `json:"ts"`
	Ts_2 int64 `json:"ts_2"`
}

type GetGlobalTrafficRow struct {
	Ts   int64           `json:"ts"`
	Up   sql.NullFloat64 `json:"up"`
	Down sql.NullFloat64 `json:"down"`
}

func (q *Queries) GetGlobalTraffic(ctx context.Context, arg GetGlobalTrafficParams) ([]GetGlobalTrafficRow, error) {
	rows, err := q.db.QueryContext(ctx, getGlobalTraffic, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalTrafficRow
	for rows.Next() {
		var i GetGlobalTrafficRow
		if err := rows.Scan(&i.Ts, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboundMeta = `-- name: GetInboundMeta :one
SELECT tag, external_port FROM inbound_meta WHERE tag = ?
`

type GetInboundMetaRow struct {
	Tag          string        `json:"tag"`
	ExternalPort sql.NullInt64 `json:"external_port"`
}

func (q *Queries) GetInboundMeta(ctx context.Context, tag string) (GetInboundMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getInboundMeta, tag)
	var i GetInboundMetaRow
	err := row.Scan(&i.Tag, &i.ExternalPort)
	return i, err
}

const getLastSeenMap = `-- name: GetLastSeenMap :many
SELECT user, MAX(ts) as max_ts FROM samples GROUP BY user
`

type GetLastSeenMapRow struct {
	User  string      `json:"user"`
	MaxTs interface{} `json:"max_ts"`
}

func (q *Queries) GetLastSeenMap(ctx context.Context) ([]GetLastSeenMapRow, error) {
	rows, err := q.db.QueryContext(ctx, getLastSeenMap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastSeenMapRow
	for rows.Next() {
		var i GetLastSeenMapRow
		if err := rows.Scan(&i.User, &i.MaxTs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastSeenUserAndThreshold = `-- name: GetLastSeenUserAndThreshold :one
SELECT MAX(ts) FROM samples WHERE user = ? AND (uplink + downlink) >= ?
`

type GetLastSeenUserAndThresholdParams struct {
	User   string `json:"user"`
	Uplink int64  `json:"uplink"`
}

func (q *Queries) GetLastSeenUserAndThreshold(ctx context.Context, arg GetLastSeenUserAndThresholdParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastSeenUserAndThreshold, arg.User, arg.Uplink)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getLastSeenUserWithTraffic = `-- name: GetLastSeenUserWithTraffic :one
SELECT MAX(ts) FROM samples WHERE user = ? AND (uplink > 0 OR downlink > 0)
`

func (q *Queries) GetLastSeenUserWithTraffic(ctx context.Context, user string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastSeenUserWithTraffic, user)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getMaxTimestamp = `-- name: GetMaxTimestamp :one
SELECT MAX(ts) FROM samples
`

func (q *Queries) GetMaxTimestamp(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxTimestamp)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getMaxTimestampForUser = `-- name: GetMaxTimestampForUser :one
SELECT MAX(ts) FROM samples WHERE user = ?
`

func (q *Queries) GetMaxTimestampForUser(ctx context.Context, user string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxTimestampForUser, user)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getPanelUser = `-- name: GetPanelUser :one
SELECT
	username,
	password_hash,
	can_read_users,
	can_write_users,
	can_read_wireguard,
	can_write_wireguard,
	can_read_config,
	can_write_config,
	can_read_settings,
	can_write_settings,
	can_read_panel_users,
	can_write_panel_users,
	can_read_logs,
	created_at,
	updated_at
FROM panel_users
WHERE username = ?
`

func (q *Queries) GetPanelUser(ctx context.Context, username string) (PanelUser, error) {
	row := q.db.QueryRowContext(ctx, getPanelUser, username)
	var i PanelUser
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.CanReadUsers,
		&i.CanWriteUsers,
		&i.CanReadWireguard,
		&i.CanWriteWireguard,
		&i.CanReadConfig,
		&i.CanWriteConfig,
		&i.CanReadSettings,
		&i.CanWriteSettings,
		&i.CanReadPanelUsers,
		&i.CanWritePanelUsers,
		&i.CanReadLogs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSamplerRuns = `-- name: GetSamplerRuns :many
SELECT ts, duration_ms, inserted, COALESCE(error,'') as error, COALESCE(source, 'sing-box') as source 
FROM sampler_runs 
ORDER BY ts DESC 
LIMIT ?
`

type GetSamplerRunsRow struct {
	Ts         int64  `json:"ts"`
	DurationMs int64  `json:"duration_ms"`
	Inserted   int64  `json:"inserted"`
	Error      string `json:"error"`
	Source     string `json:"source"`
}

func (q *Queries) GetSamplerRuns(ctx context.Context, limit int64) ([]GetSamplerRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSamplerRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSamplerRunsRow
	for rows.Next() {
		var i GetSamplerRunsRow
		if err := rows.Scan(
			&i.Ts,
			&i.DurationMs,
			&i.Inserted,
			&i.Error,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSamplesForUser = `-- name: GetSamplesForUser :many
SELECT user, ts, uplink, downlink 
FROM samples 
WHERE user = ? AND ts >= ? AND ts <= ? 
ORDER BY ts ASC
`

type GetSamplesForUserParams struct {
	User string `json:"user"`
	Ts   int64  `json:"ts"`
	Ts_2 int64  `json:"ts_2"`
}

func (q *Queries) GetSamplesForUser(ctx context.Context, arg GetSamplesForUserParams) ([]Sample, error) {
	rows, err := q.db.QueryContext(ctx, getSamplesForUser, arg.User, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.User,
			&i.Ts,
			&i.Uplink,
			&i.Downlink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, token, name, created_at, updated_at FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByToken = `-- name: GetSubscriptionByToken :one
SELECT id, token, name, created_at, updated_at FROM subscriptions WHERE token = ?
`

func (q *Queries) GetSubscriptionByToken(ctx context.Context, token string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByToken, token)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionsForUser = `-- name: GetSubscriptionsForUser :many
SELECT sub_id FROM subscription_users WHERE user_name = ?
`

func (q *Queries) GetSubscriptionsForUser(ctx context.Context, userName string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsForUser, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var sub_id int64
		if err := rows.Scan(&sub_id); err != nil {
			return nil, err
		}
		items = append(items, sub_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrafficPerUser = `-- name: GetTrafficPerUser :many
SELECT user, SUM(uplink) as up, SUM(downlink) as down
FROM samples
WHERE ts >= ? AND ts <= ?
GROUP BY user
`

type GetTrafficPerUserParams struct {
	Ts   int64 `json:"ts"`
	Ts_2 int64 `json:"ts_2"`
}

type GetTrafficPerUserRow struct {
	User string          `json:"user"`
	Up   sql.NullFloat64 `json:"up"`
	Down sql.NullFloat64 `json:"down"`
}

func (q *Queries) GetTrafficPerUser(ctx context.Context, arg GetTrafficPerUserParams) ([]GetTrafficPerUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrafficPerUser, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrafficPerUserRow
	for rows.Next() {
		var i GetTrafficPerUserRow
		if err := rows.Scan(&i.User, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT email, quota_limit, quota_period, reset_day, enabled, vmess_security, vmess_alter_id FROM users WHERE email = ?
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.Email,
		&i.QuotaLimit,
		&i.QuotaPeriod,
		&i.ResetDay,
		&i.Enabled,
		&i.VmessSecurity,
		&i.VmessAlterID,
	)
	return i, err
}

const getUsersForSubscription = `-- name: GetUsersForSubscription :many
SELECT user_name FROM subscription_users WHERE sub_id = ? ORDER BY user_name ASC
`

func (q *Queries) GetUsersForSubscription(ctx context.Context, subID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsersForSubscription, subID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_name string
		if err := rows.Scan(&user_name); err != nil {
			return nil, err
		}
		items = append(items, user_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWGBoundarySamples = `-- name: GetWGBoundarySamples :many
SELECT rx, tx FROM wg_samples WHERE public_key = ? AND ts >= ? AND ts <= ? ORDER BY ts ASC LIMIT 1
`

type GetWGBoundarySamplesParams struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Ts_2      int64  `json:"ts_2"`
}

type GetWGBoundarySamplesRow struct {
	Rx int64 `json:"rx"`
	Tx int64 `json:"tx"`
}

func (q *Queries) GetWGBoundarySamples(ctx context.Context, arg GetWGBoundarySamplesParams) ([]GetWGBoundarySamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, getWGBoundarySamples, arg.PublicKey, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWGBoundarySamplesRow
	for rows.Next() {
		var i GetWGBoundarySamplesRow
		if err := rows.Scan(&i.Rx, &i.Tx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWGLastBoundarySample = `-- name: GetWGLastBoundarySample :many
SELECT rx, tx FROM wg_samples WHERE public_key = ? AND ts >= ? AND ts <= ? ORDER BY ts DESC LIMIT 1
`

type GetWGLastBoundarySampleParams struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Ts_2      int64  `json:"ts_2"`
}

type GetWGLastBoundarySampleRow struct {
	Rx int64 `json:"rx"`
	Tx int64 `json:"tx"`
}

// Note: the descending query will need its own query name
func (q *Queries) GetWGLastBoundarySample(ctx context.Context, arg GetWGLastBoundarySampleParams) ([]GetWGLastBoundarySampleRow, error) {
	rows, err := q.db.QueryContext(ctx, getWGLastBoundarySample, arg.PublicKey, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWGLastBoundarySampleRow
	for rows.Next() {
		var i GetWGLastBoundarySampleRow
		if err := rows.Scan(&i.Rx, &i.Tx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWGTrafficSeries = `-- name: GetWGTrafficSeries :many
SELECT public_key, ts, rx, tx, COALESCE(endpoint, '') as endpoint
FROM wg_samples 
WHERE public_key = ? AND ts >= ? AND ts <= ? 
ORDER BY ts ASC 
LIMIT ?
`

type GetWGTrafficSeriesParams struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Ts_2      int64  `json:"ts_2"`
	Limit     int64  `json:"limit"`
}

type GetWGTrafficSeriesRow struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Rx        int64  `json:"rx"`
	Tx        int64  `json:"tx"`
	Endpoint  string `json:"endpoint"`
}

func (q *Queries) GetWGTrafficSeries(ctx context.Context, arg GetWGTrafficSeriesParams) ([]GetWGTrafficSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getWGTrafficSeries,
		arg.PublicKey,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWGTrafficSeriesRow
	for rows.Next() {
		var i GetWGTrafficSeriesRow
		if err := rows.Scan(
			&i.PublicKey,
			&i.Ts,
			&i.Rx,
			&i.Tx,
			&i.Endpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDailyUsage = `-- name: InsertDailyUsage :exec
INSERT INTO daily_usage (user, ts, uplink, downlink)
VALUES (?, ?, ?, ?)
ON CONFLICT(user, ts) DO UPDATE SET
uplink = uplink + excluded.uplink,
downlink = downlink + excluded.downlink
`

type InsertDailyUsageParams struct {
	User     string `json:"user"`
	Ts       int64  `json:"ts"`
	Uplink   int64  `json:"uplink"`
	Downlink int64  `json:"downlink"`
}

// Daily Usage --
func (q *Queries) InsertDailyUsage(ctx context.Context, arg InsertDailyUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertDailyUsage,
		arg.User,
		arg.Ts,
		arg.Uplink,
		arg.Downlink,
	)
	return err
}

const insertSample = `-- name: InsertSample :exec
INSERT OR IGNORE INTO samples (user, ts, uplink, downlink) VALUES (?, ?, ?, ?)
`

type InsertSampleParams struct {
	User     string `json:"user"`
	Ts       int64  `json:"ts"`
	Uplink   int64  `json:"uplink"`
	Downlink int64  `json:"downlink"`
}

func (q *Queries) InsertSample(ctx context.Context, arg InsertSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertSample,
		arg.User,
		arg.Ts,
		arg.Uplink,
		arg.Downlink,
	)
	return err
}

const insertSamplerRun = `-- name: InsertSamplerRun :exec
INSERT INTO sampler_runs (ts, duration_ms, inserted, error, source) VALUES (?, ?, ?, ?, ?)
`

type InsertSamplerRunParams struct {
	Ts         int64          `json:"ts"`
	DurationMs int64          `json:"duration_ms"`
	Inserted   int64          `json:"inserted"`
	Error      sql.NullString `json:"error"`
	Source     sql.NullString `json:"source"`
}

// Sampler Runs --
func (q *Queries) InsertSamplerRun(ctx context.Context, arg InsertSamplerRunParams) error {
	_, err := q.db.ExecContext(ctx, insertSamplerRun,
		arg.Ts,
		arg.DurationMs,
		arg.Inserted,
		arg.Error,
		arg.Source,
	)
	return err
}

const insertWGDailyUsage = `-- name: InsertWGDailyUsage :exec
INSERT INTO daily_wg_usage (public_key, ts, rx, tx)
VALUES (?, ?, ?, ?)
ON CONFLICT(public_key, ts) DO UPDATE SET
rx = rx + excluded.rx,
tx = tx + excluded.tx
`

type InsertWGDailyUsageParams struct {
	PublicKey string `json:"public_key"`
	Ts        int64  `json:"ts"`
	Rx        int64  `json:"rx"`
	Tx        int64  `json:"tx"`
}

func (q *Queries) InsertWGDailyUsage(ctx context.Context, arg InsertWGDailyUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertWGDailyUsage,
		arg.PublicKey,
		arg.Ts,
		arg.Rx,
		arg.Tx,
	)
	return err
}

const insertWGSample = `-- name: InsertWGSample :exec
INSERT INTO wg_samples (public_key, ts, rx, tx, endpoint) VALUES (?, ?, ?, ?, ?)
`

type InsertWGSampleParams struct {
	PublicKey string         `json:"public_key"`
	Ts        int64          `json:"ts"`
	Rx        int64          `json:"rx"`
	Tx        int64          `json:"tx"`
	Endpoint  sql.NullString `json:"endpoint"`
}

func (q *Queries) InsertWGSample(ctx context.Context, arg InsertWGSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertWGSample,
		arg.PublicKey,
		arg.Ts,
		arg.Rx,
		arg.Tx,
		arg.Endpoint,
	)
	return err
}

const pruneSamplesOlderThan = `-- name: PruneSamplesOlderThan :exec
DELETE FROM samples WHERE ts < ?
`

func (q *Queries) PruneSamplesOlderThan(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, pruneSamplesOlderThan, ts)
	return err
}

const pruneWGSamplesOlderThan = `-- name: PruneWGSamplesOlderThan :exec
DELETE FROM wg_samples WHERE ts < ?
`

func (q *Queries) PruneWGSamplesOlderThan(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, pruneWGSamplesOlderThan, ts)
	return err
}

const regenerateSubscriptionToken = `-- name: RegenerateSubscriptionToken :exec
UPDATE subscriptions SET token = ?, updated_at = strftime('%s','now') WHERE id = ?
`

type RegenerateSubscriptionTokenParams struct {
	Token string `json:"token"`
	ID    int64  `json:"id"`
}

func (q *Queries) RegenerateSubscriptionToken(ctx context.Context, arg RegenerateSubscriptionTokenParams) error {
	_, err := q.db.ExecContext(ctx, regenerateSubscriptionToken, arg.Token, arg.ID)
	return err
}

const removeUserFromSubscription = `-- name: RemoveUserFromSubscription :exec
DELETE FROM subscription_users WHERE sub_id = ? AND user_name = ?
`

type RemoveUserFromSubscriptionParams struct {
	SubID    int64  `json:"sub_id"`
	UserName string `json:"user_name"`
}

func (q *Queries) RemoveUserFromSubscription(ctx context.Context, arg RemoveUserFromSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromSubscription, arg.SubID, arg.UserName)
	return err
}

const renameInboundMeta = `-- name: RenameInboundMeta :exec
UPDATE inbound_meta SET tag = ? WHERE tag = ?
`

type RenameInboundMetaParams struct {
	Tag   string `json:"tag"`
	Tag_2 string `json:"tag_2"`
}

func (q *Queries) RenameInboundMeta(ctx context.Context, arg RenameInboundMetaParams) error {
	_, err := q.db.ExecContext(ctx, renameInboundMeta, arg.Tag, arg.Tag_2)
	return err
}

const truncateSamples = `-- name: TruncateSamples :exec
DELETE FROM samples
`

func (q *Queries) TruncateSamples(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateSamples)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins SET password_hash = ? WHERE username = ?
`

type UpdateAdminPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.Username)
	return err
}

const updateAdminUsername = `-- name: UpdateAdminUsername :exec
UPDATE admins SET username = ? WHERE username = ?
`

type UpdateAdminUsernameParams struct {
	Username   string `json:"username"`
	Username_2 string `json:"username_2"`
}

func (q *Queries) UpdateAdminUsername(ctx context.Context, arg UpdateAdminUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUsername, arg.Username, arg.Username_2)
	return err
}

const updatePanelUserPassword = `-- name: UpdatePanelUserPassword :exec
UPDATE panel_users SET password_hash = ?, updated_at = strftime('%s','now') WHERE username = ?
`

type UpdatePanelUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

func (q *Queries) UpdatePanelUserPassword(ctx context.Context, arg UpdatePanelUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePanelUserPassword, arg.PasswordHash, arg.Username)
	return err
}

const updatePanelUserPermissions = `-- name: UpdatePanelUserPermissions :exec
UPDATE panel_users
SET
	can_read_users = ?,
	can_write_users = ?,
	can_read_wireguard = ?,
	can_write_wireguard = ?,
	can_read_config = ?,
	can_write_config = ?,
	can_read_settings = ?,
	can_write_settings = ?,
	can_read_panel_users = ?,
	can_write_panel_users = ?,
	can_read_logs = ?,
	updated_at = strftime('%s','now')
WHERE username = ?
`

type UpdatePanelUserPermissionsParams struct {
	CanReadUsers       int64  `json:"can_read_users"`
	CanWriteUsers      int64  `json:"can_write_users"`
	CanReadWireguard   int64  `json:"can_read_wireguard"`
	CanWriteWireguard  int64  `json:"can_write_wireguard"`
	CanReadConfig      int64  `json:"can_read_config"`
	CanWriteConfig     int64  `json:"can_write_config"`
	CanReadSettings    int64  `json:"can_read_settings"`
	CanWriteSettings   int64  `json:"can_write_settings"`
	CanReadPanelUsers  int64  `json:"can_read_panel_users"`
	CanWritePanelUsers int64  `json:"can_write_panel_users"`
	CanReadLogs        int64  `json:"can_read_logs"`
	Username           string `json:"username"`
}

func (q *Queries) UpdatePanelUserPermissions(ctx context.Context, arg UpdatePanelUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, updatePanelUserPermissions,
		arg.CanReadUsers,
		arg.CanWriteUsers,
		arg.CanReadWireguard,
		arg.CanWriteWireguard,
		arg.CanReadConfig,
		arg.CanWriteConfig,
		arg.CanReadSettings,
		arg.CanWriteSettings,
		arg.CanReadPanelUsers,
		arg.CanWritePanelUsers,
		arg.CanReadLogs,
		arg.Username,
	)
	return err
}

const updatePanelUsername = `-- name: UpdatePanelUsername :exec
UPDATE panel_users SET username = ?, updated_at = strftime('%s','now') WHERE username = ?
`

type UpdatePanelUsernameParams struct {
	Username   string `json:"username"`
	Username_2 string `json:"username_2"`
}

func (q *Queries) UpdatePanelUsername(ctx context.Context, arg UpdatePanelUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updatePanelUsername, arg.Username, arg.Username_2)
	return err
}

const updateSubscriptionName = `-- name: UpdateSubscriptionName :exec
UPDATE subscriptions SET name = ?, updated_at = strftime('%s','now') WHERE id = ?
`

type UpdateSubscriptionNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateSubscriptionName(ctx context.Context, arg UpdateSubscriptionNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionName, arg.Name, arg.ID)
	return err
}

const updateWGPeerHandshake = `-- name: UpdateWGPeerHandshake :exec
UPDATE wg_peers
SET last_handshake = ?, updated_at = strftime('%s','now')
WHERE public_key = ?
`

type UpdateWGPeerHandshakeParams struct {
	LastHandshake sql.NullInt64 `json:"last_handshake"`
	PublicKey     string        `json:"public_key"`
}

func (q *Queries) UpdateWGPeerHandshake(ctx context.Context, arg UpdateWGPeerHandshakeParams) error {
	_, err := q.db.ExecContext(ctx, updateWGPeerHandshake, arg.LastHandshake, arg.PublicKey)
	return err
}

const upsertInboundMeta = `-- name: UpsertInboundMeta :exec
INSERT INTO inbound_meta (tag, external_port) VALUES (?, ?) ON CONFLICT(tag) DO UPDATE SET external_port = excluded.external_port
`

type UpsertInboundMetaParams struct {
	Tag          string        `json:"tag"`
	ExternalPort sql.NullInt64 `json:"external_port"`
}

// InboundMeta Queries --
func (q *Queries) UpsertInboundMeta(ctx context.Context, arg UpsertInboundMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertInboundMeta, arg.Tag, arg.ExternalPort)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (email, quota_limit, quota_period, reset_day, enabled, vmess_security, vmess_alter_id) 
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(email) DO UPDATE SET
	quota_limit = excluded.quota_limit,
	quota_period = excluded.quota_period,
	reset_day = excluded.reset_day,
	enabled = excluded.enabled,
	vmess_security = excluded.vmess_security,
	vmess_alter_id = excluded.vmess_alter_id
`

type UpsertUserParams struct {
	Email         string         `json:"email"`
	QuotaLimit    sql.NullInt64  `json:"quota_limit"`
	QuotaPeriod   sql.NullString `json:"quota_period"`
	ResetDay      sql.NullInt64  `json:"reset_day"`
	Enabled       sql.NullInt64  `json:"enabled"`
	VmessSecurity sql.NullString `json:"vmess_security"`
	VmessAlterID  sql.NullInt64  `json:"vmess_alter_id"`
}

// Users / Metadata --
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.Email,
		arg.QuotaLimit,
		arg.QuotaPeriod,
		arg.ResetDay,
		arg.Enabled,
		arg.VmessSecurity,
		arg.VmessAlterID,
	)
	return err
}

const upsertWGPeer = `-- name: UpsertWGPeer :exec
INSERT INTO wg_peers (public_key, alias, deleted, updated_at)
VALUES (?, ?, ?, strftime('%s','now'))
ON CONFLICT(public_key) DO UPDATE SET
	alias = excluded.alias,
	deleted = excluded.deleted,
	updated_at = strftime('%s','now')
`

type UpsertWGPeerParams struct {
	PublicKey string        `json:"public_key"`
	Alias     string        `json:"alias"`
	Deleted   sql.NullInt64 `json:"deleted"`
}

// WG Peers --
func (q *Queries) UpsertWGPeer(ctx context.Context, arg UpsertWGPeerParams) error {
	_, err := q.db.ExecContext(ctx, upsertWGPeer, arg.PublicKey, arg.Alias, arg.Deleted)
	return err
}
